### PR TITLE
fix: `filters` not working for the save dialog

### LINKED ISSUE #1073: Problem at the moment of Export the archive,
When I save an archive, it exports as a '.archive' file, but it can't be opened with any program, including Rnote. This issue occurs most of the time, although occasionally it works. Additionally, today I encountered problems when saving the PDF archive. I'm working with Rnote Version 0.10.0 on Windows 11.

### PR DESCRIPTION
**Pull request by Doublonmousse**
To fix #1073 .

Makes the filter on the save dialog work. 

image

Before this the `file type` part was empty (filter not applied) leading to various potential errors, including the possibility to create files that have no extension.

### CODE REVIEW

**Comment by flxzt** [comment]
Thanks a lot! Adding `filters()` before using `default_filter()` is  missing in several places in the code, do you want to fix this everywhere?

**Comment by Doublonmousse** [comment]
On it. For now I'm doing it kinda "naively" for the export part (meaning that there's a single filter shown for `.svg` if `svg` is selected in the previous export window, but there is no bidirectional link that would allow to change the file type in the file chooser window to say, a `.pdf` file and have the change propagated back into the application)

**Comment by Doublonmousse** [comment]
I do get some 
```
(rnote:36736): Gtk-WARNING **: 13:05:01.848: gtk_file_chooser_add_filter() called on filter already in list
```
for the import file dialog somehow.

**Comment by flxzt** [comment]
`ListStore`'s are also deprecated..

But I'd prefer to keep it a single filter anyway, because then it is immediatly clear what is importable - everything that is visibily listed in the filepicker

File: crates/rnote-ui/src/dialogs/import.rs [hunk 1]
```diff
@@ -46,27 +50,43 @@ pub(crate) async fn filedialog_open_doc(appwindow: &RnAppWindow) {
...
+    filters_vec[4].add_suffix("jpg");
+    filters_vec[4].add_suffix("jpeg");
+    filters_vec[4].set_name(Some(&gettext("Jpg")));
+
+    filters_vec[5].add_mime_type("text/plain");
+    filters_vec[5].add_suffix("txt");
+    filters_vec[5].set_name(Some(&gettext("Txt")));
+
+    // append all these filters to the gio::ListStore
+    filters_vec.iter().for_each(|filter| filters.append(filter));
```
Comment (Doublonmousse) [inline crates/rnote-ui/src/dialogs/import.rs:83]: I'll revert this part (to use one filter here) and re check if the error persists.

**Comment by Doublonmousse** [comment]
Is it ? On gtk-rs `gtk4::ListStore` is shown as deprecated, with `gio::ListStore` to use instead.

**Comment by flxzt** [comment]
My bad, `gio::ListStore` is not

File: crates/rnote-ui/src/dialogs/import.rs (hunk 1 above)
Comment (flxzt) [reply crates/rnote-ui/src/dialogs/import.rs:83]: Ok, sounds good!

**Comment by flxzt** [comment]
Works now for me. Thanks for this fix :)
